# Generated by Django 5.0 on 2023-12-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_appuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Location Email'),
        ),
    ]
