# Generated by Django 5.0 on 2023-12-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_location_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Location Email'),
        ),
        migrations.AlterField(
            model_name='location',
            name='website',
            field=models.URLField(blank=True, max_length=255, verbose_name='Location Website'),
        ),
    ]
