# Generated by Django 5.0 on 2023-12-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_location_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='location image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='events.appuser'),
        ),
    ]
