# Generated by Django 4.2.8 on 2023-12-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_location_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='location image'),
        ),
    ]
